"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import burger as shared_burger
from typing import Optional



@dataclasses.dataclass
class CreateBurgerResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    burger: Optional[shared_burger.Burger] = dataclasses.field(default=None)
    r"""The burger was created successfully."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

