"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import dateutil.parser
import requests as requests_http
from dataclasses_json import Undefined, dataclass_json
from datetime import datetime
from enum import Enum
from marshmallow import fields
from sdk import utils
from typing import Optional



@dataclasses.dataclass
class GetOrderRequest:
    id: float = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    


class GetOrder200ApplicationJSONStatus(str, Enum):
    r"""The status of the order."""
    PENDING = 'pending'
    IN_PROGRESS = 'in_progress'
    READY = 'ready'
    DELIVERED = 'delivered'


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class GetOrder200ApplicationJSON:
    r"""The order was retrieved successfully."""
    burger_ids: list[float] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('burger_ids') }})
    r"""The burgers in the order."""
    id: float = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    r"""The unique identifier of the order."""
    status: GetOrder200ApplicationJSONStatus = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status') }})
    r"""The status of the order."""
    table: float = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('table') }})
    r"""The table the order is for."""
    time: datetime = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('time'), 'encoder': utils.datetimeisoformat(False), 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso') }})
    r"""The time the order was placed."""
    note: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('note'), 'exclude': lambda f: f is None }})
    r"""A note for the order."""
    




@dataclasses.dataclass
class GetOrderResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    get_order_200_application_json_object: Optional[GetOrder200ApplicationJSON] = dataclasses.field(default=None)
    r"""The order was retrieved successfully."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

