"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import burger as shared_burger
from typing import Optional



@dataclasses.dataclass
class ListBurgersResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    burgers: Optional[list[shared_burger.Burger]] = dataclasses.field(default=None)
    r"""The burgers were retrieved successfully."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

