"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import burger as shared_burger
from ..shared import burgerupdate as shared_burgerupdate
from typing import Optional



@dataclasses.dataclass
class UpdateBurgerRequest:
    id: float = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    burger_update: Optional[shared_burgerupdate.BurgerUpdate] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    r"""The burger to update."""
    




@dataclasses.dataclass
class UpdateBurgerResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    burger: Optional[shared_burger.Burger] = dataclasses.field(default=None)
    r"""The burger was updated successfully."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

